services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.docker
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - shortlink-network

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: shortlink
      POSTGRES_PASSWORD: shortlink
      POSTGRES_DB: shortlink
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - shortlink-network

  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    networks:
      - shortlink-network

volumes:
  postgres-data:
  redis-data:

networks:
  shortlink-network:
    driver: bridge
